meta_product_name: "Kingsley Lau"
meta_title: "Kingsley Lau - Hong Kong based fullstack web developer."
meta_description: "Hong Kong-based web developer with expertise in Ruby on Rails, HTML, CSS, ES6, SQL."
meta_image: "Profile-og.jpg"
twitter_account: "@KingsleyLau1"
